server:
  port: 8080

spring:
  # thymeleaf模板配置
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    # 热部署文件，页面不产生缓存，及时更新
    cache: false
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
  datasource:
    # 数据库连接配置信息
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/corporate_training?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 1234
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # http://localhost:8080/druid
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化时建立物理连接的个数
      initialSize: 1
      # 最小连接池数量
      minIdle: 1
      # 最大连接池数量 maxIdle已经不再使用
      maxActive: 20
      # 配置获取连接等待超时的时间，单位毫秒
      maxWait: 60000
      #申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      testWhileIdle: true
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，既作为检测的间隔时间又作为testWhileIdel执行的依据，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间（销毁线程时检测当前连接的最后活动时间和当前时间差大于该值时，关闭当前连接），单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置测试查询语句，用来检测连接是否有效的sql，必须是一个查询语句
      # mysql中为 select 'x'
      # oracle中为 select 1 from dual
      validationQuery: select 'x'
      # 申请连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      testOnBorrow: false
      # 归还连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      testOnReturn: false
      # 是否缓存preparedStatement,mysql5.5+建议开启
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      # 配置监控统计拦截的filters扩展插件，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j2
      # 配置DruidStatFilter
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      # 配置DruidStatViewServlet
      stat-view-servlet:
        url-pattern: "/druid/*"
        # IP白名单(没有配置或者为空，则允许所有访问)
        allow: 127.0.0.1,192.168.163.1
        # IP黑名单 (存在共同时，deny优先于allow)
        deny: 192.168.1.73
        # 禁用HTML页面上的“Reset All”功能
        reset-enable: false
        # 设置访问druid监控页的账号和密码,默认没有
        # 登录名
        login-username: admin
        # 登录密码
        login-password: 123456
      filter:
        stat:
          log-slow-sql: true

# Mybatis数据库映射文件配置
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.mallotec.reb.corporatetraining.pojo